### ISSUE TITLE
Why do you need to log?

### ISSUE THREAD

**Issue by shiryz** [FACN8/Like#36]
https://github.com/FACN8/Like/blob/master/src/app.js#L18-L24

Are you checking your log file? do you need to see what's going on behind the scenes?

- You can add it and not push it

**Comment by FrancisA2000** [comment]
greetings @shiryz 
At first we wanted to get the user IP, so we can track it, and know witch user is online to get his ID for the database.
But at the end we didn't have enough time, so yeah we should remove it now.
